language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: erMY7sNOrLB3EKRA09Z5CkA29xVtFpsL2ca5hyukiE5LUk68DWz4yx305NWvgsrogN4cmO9W147tME+UjNQF2XUZC7hnkkE2KofPp/lGRaWgesWOVTCpiGlWczkycmqv7uOwTASPO5mvit6uMfkONnASBcnW/oc/5ZtMCiqWIM8=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: BNWTaO36BvdfHf2hBB7lnZ0J0NRz/i0l+qHxRHVaF2/lxqC3zn/OjU8RPefwYsoTp2L+N2NqRdUv1JoLCYjOjFiRTCtB4v4FkK+gYF95mHwALdj7Tkmhkobu+PI+eHV3/ZSAWP5O43FxkNO17vxmKgq+1+X914NcFonHfvDju+A=
sudo: false
